# Generated by Django 4.0.2 on 2022-02-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_auto_20220211_1857'),
        ('terms', '0002_auto_20220213_1542'),
    ]

    operations = [
    ]
