# Generated by Django 3.1.3 on 2022-02-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_auto_20220213_1542'),
        ('terms', '0002_auto_20220211_1857'),
    ]

    operations = [
    ]
