# Generated by Django 3.1.3 on 2022-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
                ('rent_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'month_busan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthDaejeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
                ('rent_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'month_daejeon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthGyeonggi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
                ('rent_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'month_gyeonggi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthIncheon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
                ('rent_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'month_incheon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthSeoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
                ('rent_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'month_seoul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg1', models.CharField(max_length=200)),
                ('reg2', models.CharField(max_length=200)),
                ('reg3', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
    ]
