# Generated by Django 3.1.3 on 2022-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'sell_busan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellDaejeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'sell_daejeon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellGyeonggi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'sell_gyeonggi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellIncheon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'sell_incheon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellSeoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('menuGubun', models.CharField(max_length=100)),
                ('bldg_nm', models.CharField(max_length=200)),
                ('bldg_area', models.FloatField(max_length=100)),
                ('year', models.IntegerField()),
                ('deal_mm', models.IntegerField()),
                ('sum_amt', models.IntegerField()),
            ],
            options={
                'db_table': 'sell_seoul',
                'managed': False,
            },
        ),
    ]
